### ISSUE TITLE
[Feature] Adding more drawing capabilities on the images

### ISSUE THREAD

**Issue by NEKolev** [olive-groves/butterfly_viewer#63]
### Is there an existing request for this feature?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Adding more drawing capabilities on the images. For example:
- Rectangle, circular enclosure. 
- Enclosure with a number (1, 2, 3). It would be nice if the number is unique for each image. For example, enclosing one area and marking everywhere with number 1. 
- Arrow/line with and without a number, which can be aligned horizontally, at 45 degrees, and vertically, for example, by pressing Shift on the keyboard during drawing.

It would also be nice to be able to change the color of the drawn, as well as the size.

**Comment by larsmaxfield** [comment]
Great feature that I don't have time to work on, at least for the foreseeable future.

On the frontend these drawing tools are straightforward, but on the backend they require a lot of effort to function really well. And by "really well" I mean the level of quality of PowerPoint or Miro. And that's the level of quality I would want in the Viewer. Anything less I would find annoying, because bad drawing tools are really, _really_ annoying.

Perhaps with some searching I can find a premade library of drawing widgets for PyQt which would satisfy the requirements, but there would still be a some work to implement it all.

Will update here if things change!
