### ISSUE TITLE
[Feature] Recording a GIF or video with Sliding overlay

### ISSUE THREAD

**Issue by NEKolev** [olive-groves/butterfly_viewer#64]
### Is there an existing request for this feature?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Recording a GIF or video with Sliding overlay. 

https://github.com/olive-groves/butterfly_viewer/assets/70388317/bbb89543-fcbc-4a20-87ad-3663ddaa1d9a

Of course, only the overlaid images themselves without the frame of the program :)

**Comment by NEKolev** [comment]
I made a lot of Issues, but last but not least, I want to tell you that your program is wonderful. I really like the minimalist style and the way it works. I would recommend you to take a look at this project https://github.com/OpenNumismat/ImageEditor. It is part of the OpenNumismat program, which is the best program for collectors. I think you can find useful things.

**Comment by larsmaxfield** [comment]
I won't add this because there are already great existing screencapture tools :-)

I use [ScreenToGif](https://www.screentogif.com/) to record all my GIFs. You could achieve your feature by using it like this:

1. ScreenToGif: Auto-fit the recorder to the Viewer window
2. Viewer: Turn off the interface
3. ScreenToGif: Record the video
4. ScreenToGif: Crop out the frame of the Viewer window

The only currently annoying thing about this strategy is that the buttons on the bottom right of the Viewer persist even when the interface is hidden. You could always crop that part out, too, or you could make a feature request to hide _all_ interface items :-)

**Comment by larsmaxfield** [comment]
> I made a lot of Issues, but last but not least, I want to tell you that your program is wonderful. I really like the minimalist style and the way it works. I would recommend you to take a look at this project https://github.com/OpenNumismat/ImageEditor. It is part of the [OpenNumismat ](https://github.com/OpenNumismat/open-numismat) program, which is the best program for collectors. I think you can find useful things.

Thanks for comments and issues. I'm glad the majority of them are features, not bugs ;-)

The thumbnail gallery view of https://github.com/OpenNumismat/ImageEditor is neat. That layout is what I envision if/when that feature gets added to the Viewer. As for image editing I may leave that to other apps unless there's a good reason, but even then it may be added instead to Butterfly Registrator (or I simply join those two into one app...)
